import { Document, Note, Goal } from '../types';

export const SEED_DOCUMENTS: Document[] = [
  {
    id: 'doc-1',
    title: 'Attention Is All You Need',
    type: 'research_paper',
    status: 'read',
    source: {
      type: 'url',
      uri: 'https://arxiv.org/abs/1706.03762',
      fileName: 'vaswani2017attention.pdf',
    },
    tags: ['CO5430', 'machine-learning', 'transformers', 'deep-learning'],
    linked_project: '3YP Swarm Robotics',
    priority: 'high',
    added_date: '2026-08-15T09:00:00.000Z',
    started_date: '2026-08-16T14:30:00.000Z',
    completed_date: '2026-08-20T18:00:00.000Z',
    progress: 100,
    rating: 5,
    authors: 'Ashish Vaswani, Noam Shazeer, Niki Parmar, et al.',
    year: 2017,
    venue: 'NeurIPS 2017',
    doi: '10.48550/arXiv.1706.03762',
  },
  {
    id: 'doc-2',
    title: 'A Large Dataset to Train Convolutional Networks for Disparity, Optical Flow, and Scene Flow Estimation',
    type: 'research_paper',
    status: 'in_progress',
    source: {
      type: 'url',
      uri: 'https://arxiv.org/abs/1512.02134',
      fileName: 'mayer2016dispnet.pdf',
    },
    tags: ['computer-vision', 'stereo-vision', 'disparity-estimation', 'CO5430'],
    linked_project: 'CV Stereo Disparity Project',
    priority: 'high',
    added_date: '2026-08-22T11:15:00.000Z',
    started_date: '2026-08-25T10:00:00.000Z',
    progress: 65,
    authors: 'Nikolaus Mayer, Eddy Ilg, Philip Häusser, et al.',
    year: 2016,
    venue: 'CVPR 2016',
    doi: '10.1109/CVPR.2016.438',
  },
  {
    id: 'doc-3',
    title: 'Computer Vision: Algorithms and Applications (2nd Edition)',
    type: 'book',
    status: 'in_progress',
    source: {
      type: 'url',
      uri: 'http://szeliski.org/Book/',
      fileName: 'szeliski_computer_vision_2nd_ed.pdf',
    },
    tags: ['computer-vision', 'reference', 'textbook', 'stereo-vision'],
    linked_project: 'CV Stereo Disparity Project',
    priority: 'medium',
    added_date: '2026-08-10T08:00:00.000Z',
    started_date: '2026-08-12T09:00:00.000Z',
    progress: 38,
    current_page: 355,
    total_pages: 940,
    authors: 'Richard Szeliski',
    year: 2022,
    venue: 'Springer',
  },
  {
    id: 'doc-4',
    title: 'CO5430 Advanced Embedded Systems - Module 4: Real-Time Operating Systems & Scheduling',
    type: 'course_material',
    status: 'in_progress',
    source: {
      type: 'physical',
      location: 'CompEng Dept Folder / Lecture Binder',
    },
    tags: ['CO5430', 'embedded-systems', 'rtos', 'scheduling'],
    priority: 'high',
    added_date: '2026-08-28T14:00:00.000Z',
    started_date: '2026-09-01T16:00:00.000Z',
    progress: 50,
    current_page: 45,
    total_pages: 90,
  },
  {
    id: 'doc-5',
    title: 'Swarm Robotics: A Review from the Perspective of Distributed Artificial Intelligence',
    type: 'research_paper',
    status: 'to_read',
    source: {
      type: 'url',
      uri: 'https://www.frontiersin.org/articles/10.3389/frobt.2020.00069/full',
    },
    tags: ['swarm-robotics', 'distributed-systems', 'multi-agent'],
    linked_project: '3YP Swarm Robotics',
    priority: 'high',
    added_date: '2026-09-02T10:30:00.000Z',
    progress: 0,
    authors: 'Manuele Brambilla, Eliseo Ferrante, Mauro Birattari, Marco Dorigo',
    year: 2020,
    venue: 'Frontiers in Robotics and AI',
    doi: '10.3389/frobt.2020.00069',
  },
  {
    id: 'doc-6',
    title: 'Designing Data-Intensive Applications: The Big Ideas Behind Reliable, Scalable, and Maintainable Systems',
    type: 'book',
    status: 'read',
    source: {
      type: 'url',
      uri: 'https://dataintensive.net/',
    },
    tags: ['distributed-systems', 'database', 'system-design'],
    priority: 'medium',
    added_date: '2026-07-01T12:00:00.000Z',
    started_date: '2026-07-05T09:00:00.000Z',
    completed_date: '2026-08-28T22:00:00.000Z',
    progress: 100,
    current_page: 560,
    total_pages: 560,
    rating: 5,
    authors: 'Martin Kleppmann',
    year: 2017,
    venue: "O'Reilly Media",
  },
  {
    id: 'doc-7',
    title: 'CO5420 Distributed Algorithms - Consensus & Raft Protocol Notes',
    type: 'course_material',
    status: 'to_read',
    source: {
      type: 'google_drive',
      uri: 'https://drive.google.com/drive/u/0/folders/my-course-notes-co5420',
      fileName: 'CO5420_Consensus_Raft.pdf',
    },
    tags: ['CO5420', 'distributed-systems', 'consensus', 'raft'],
    priority: 'medium',
    added_date: '2026-09-03T15:45:00.000Z',
    progress: 0,
    total_pages: 35,
  },
];

export const SEED_NOTES: Note[] = [
  {
    id: 'note-1',
    document_id: 'doc-1',
    content: 'Key concept: Self-attention scales with sequence length quadratically O(N^2) in memory, but dot-product computation is heavily parallelizable unlike RNNs.',
    created_at: '2026-08-17T15:30:00.000Z',
  },
  {
    id: 'note-2',
    document_id: 'doc-1',
    content: 'Multi-Head Attention projects queries, keys, and values h times with learned linear projections. Very useful for aggregating sensory vectors across robot swarms!',
    created_at: '2026-08-19T11:20:00.000Z',
  },
  {
    id: 'note-3',
    document_id: 'doc-2',
    content: 'DispNet uses an explicit 1D correlation layer along the epipolar line. This substantially reduces search complexity compared to 2D generic optical flow.',
    created_at: '2026-08-26T16:45:00.000Z',
  },
  {
    id: 'note-4',
    document_id: 'doc-2',
    content: 'Synthetic dataset "FlyingThings3D" was crucial for pre-training before fine-tuning on KITTI stereo benchmark. Need to note this for our 3YP methodology section.',
    created_at: '2026-08-27T09:15:00.000Z',
  },
  {
    id: 'note-5',
    document_id: 'doc-3',
    content: 'Chapter 11 covers epipolar geometry and stereo matching. Rectification is essential before applying disparity estimation to align scanlines horizontally.',
    created_at: '2026-08-14T20:10:00.000Z',
  },
  {
    id: 'note-6',
    document_id: 'doc-4',
    content: 'Rate Monotonic Scheduling (RMS) is optimal for static priority, whereas Earliest Deadline First (EDF) achieves 100% processor utilization for independent periodic tasks.',
    created_at: '2026-09-02T18:00:00.000Z',
  },
];

export const SEED_GOALS: Goal[] = [
  {
    id: 'goal-1',
    title: 'Read 3 Papers for 3YP Swarm Robotics Proposal',
    target_count: 3,
    current_count: 1, // doc-1 is read, doc-5 is to_read
    deadline: '2026-10-15',
    linked_project: '3YP Swarm Robotics',
    status: 'active',
  },
  {
    id: 'goal-2',
    title: 'Finish 2 CV Stereo Disparity Project References',
    target_count: 2,
    current_count: 0, // doc-2 and doc-3 in progress
    deadline: '2026-09-30',
    linked_project: 'CV Stereo Disparity Project',
    status: 'active',
  },
  {
    id: 'goal-3',
    title: 'Complete CO5430 Course Reading Materials',
    target_count: 2,
    current_count: 1, // doc-1 has CO5430 tag and is read
    deadline: '2026-09-25',
    linked_tag: 'CO5430',
    status: 'active',
  },
];
